# Generated by Django 3.2 on 2021-04-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votehere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='votedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted', models.IntegerField()),
            ],
        ),
    ]
